### ISSUE TITLE
混淆错误

### ISSUE THREAD

**Issue by Ludejin** [jaikydota/Android-ImagesPickers#6]
![image](https://cloud.githubusercontent.com/assets/10751355/20620651/b18763ec-b335-11e6-81de-cf2b1fcb1038.png)

**Comment by jaikydota** [comment]
Please print your log in full

**Comment by Ludejin** [comment]
it is not this lib error, i am so sorry!

**Comment by jaikydota** [comment]
No big deal, welcome comments
